### ISSUE TITLE
issue with sparse matrices

### ISSUE THREAD

**Issue by jkanche** [fionarhuang/TreeSummarizedExperiment#10]
I'm using the pbmc 3k single cell dataset from the seurat package to create a `TreeSummarizedExperiment` class. The count matrix is a sparse matrix and fails when i try to use `aggValue` on this line - 

https://github.com/fionarhuang/TreeSummarizedExperiment/blob/master/R/aggValue.R#L201

If i coerce the sparse matrix to a normal matrix, it works. . Also out of curiosity, whats the advantage of transposing a matrix using lapply vs using the transpose function directly on the matrix -  `t(mat)` ?

**Comment by fionarhuang** [comment]
`lapply(mat, t)` is used instead of `t(mat)` because `mat` is a list of matrices. Would you be interested to help on extending the `aggValue` to work on sparse matrix? I would be happy to add collaborators.

**Comment by jkanche** [comment]
sure, I can definitely help with this
