### ISSUE TITLE
TaxonomyTable?

### ISSUE THREAD

**Issue by lwaldron** [fionarhuang/TreeSummarizedExperiment#2]
Perhaps define an alternative to phyloseq::taxonomyTable that derives from `DataFrame`, contains required columns from tree of life plus additional optional columns, and has a show method akin to `GRanges`? This could then be used in the `rowData`. 

https://github.com/joey711/phyloseq/blob/cd7da46693026895686ae30014c40735f9e88c28/R/allClasses.R#L58

**Comment by fionarhuang** [comment]
In current structure, the taxonomic table could be directly added to the right part of the 

> Perhaps define an alternative to phyloseq::taxonomyTable that derives from `DataFrame`, contains required columns from tree of life plus additional optional columns, and has a show method akin to `GRanges`? This could then be used in the `rowData`.
> 
> https://github.com/joey711/phyloseq/blob/cd7da46693026895686ae30014c40735f9e88c28/R/allClasses.R#L58

Thanks for the suggestion!
In current structure, the taxonomic table could directly go to the right part of the `rowData`. Probably there is a special reason that you would like it to be in the left part (`LinkData`) of the `rowData`? 

Here is a toy example.

`
#### The taxonomic table
taxTab <- data.frame(Kindom = rep("A", 5),
                     Phylum = c("B1", rep("B2", 4)),
                     Class = c("C1", "C2", "C3", "C3", NA),
                     OTU = c("D1", "D2", "D3", "D4", NA))

#### count table
set.seed(1)
toyTable <- matrix(rnbinom(20, size = 1, mu = 10), nrow = 5)
colnames(toyTable) <- paste(rep(LETTERS[1:2], each = 2), 
                            rep(1:2, 2), sep = "_")
rownames(toyTable) <- paste("entity", seq_len(5), sep = "")

toyTable

#### convert to a phylo tree
taxTree <- toTree(data = taxTab, cache = FALSE)

#### construct a TreeSummarizedExperiment object
rowInf$nodeLab <- taxTree$tip.label
taxTSE <- TreeSummarizedExperiment(assays = list(toyTable),
                                   rowData = rowInf,
                                   rowTree = taxTree)

rowData(taxTSE)

#### add original taxonomic table to the row data
df <- DataFrame(rowData(taxTSE), taxTab)
lk <- LinkDataFrame(LinkData = linkData(taxTSE), df)
rowData(taxTSE) <- lk
`
The hierarchical information required to do aggregation is already kept in the `taxTree`.

**Comment by fionarhuang** [comment]
Hi @lwaldron ,

Should I close this issue now?

**Comment by lwaldron** [comment]
Yes, done.
