### ISSUE TITLE
Subsetting by rownames is not available

### ISSUE THREAD

**Issue by FelixErnst** [fionarhuang/TreeSummarizedExperiment#30]
Hi,

subsetting by rownames does not work for `TreeSummarizedExperiment`.

```
data("tinyTree")
# the count table
count <- matrix(rpois(100, 50), nrow = 10)
rownames(count) <- c(tinyTree$tip.label)
colnames(count) <- paste("C_", 1:10, sep = "_")
# The sample information
sampC <- data.frame(condition = rep(c("control", "trt"), each = 5),
                                     gender = sample(x = 1:2, size = 10, replace = TRUE))
rownames(sampC) <- colnames(count)
# build a TreeSummarizedExperiment object
tse <- TreeSummarizedExperiment(assays = list(count),
                                    colData = sampC,
                                    rowTree = tinyTree)

# does not work
tse["t2",]
```

The reason for this is, that the rownames on the `LinkDataFrame` objects are not set.

Felix

**Comment by fionarhuang** [comment]
Hi @FelixErnst ,

Thanks for helping to fix the bug. I add some edits to allow more flexibly subsetting when using characters (e.g., rownames, node labels, alias labels of node). The use of alias labels is for the tree that has some nodes without labels or sharing a labels.

If you are interested to add your name as a contributor in the [description](https://github.com/fionarhuang/TreeSummarizedExperiment/blob/master/DESCRIPTION) file, I would be happy to merge the PR afterwards :)

**Comment by fionarhuang** [comment]
One example is as below:
 
```
suppressPackageStartupMessages({
    library(TreeSummarizedExperiment)
    library(ggtree)
})

set.seed(1)
Tree <- ape::rtree(10)
ggtree(Tree, branch.length = "none") +
    geom_text2(aes(label = label)) +
    geom_text2(aes(label = node), color = "red", nudge_x = -0.1)

# node 11 is an internal node
# There is no labels of internal nodes of Tree
Tree$node.label


# the count table
count <- matrix(rpois(110, 50), nrow = 11)
rownames(count) <- transNode(tree = Tree, node = 1:11,
                             use.alias = TRUE)
colnames(count) <- paste("C_", 1:10, sep = "_")


# The sample information
sampC <- data.frame(condition = rep(c("control", "trt"), 
                                    each = 5),
                    gender = sample(x = 1:2, size = 10, 
                                    replace = TRUE))
rownames(sampC) <- colnames(count)

# build a TreeSummarizedExperiment object
# rowNodeLab is specified to tell which rows of count should match which nodes of the tree
lse <- TreeSummarizedExperiment(assays = list(count),
                                colData = sampC,
                                rowTree = Tree,
                                rowNodeLab = rownames(count))


# This should give the same result: node 9
lse["alias_9", ]
lse["t10", ]

rowLinks(lse["alias_9", ])
rowLinks(lse["t10", ])
```

**Comment by FelixErnst** [comment]
Hi @fionarhuang,

thanks for the reply and accepting the general idea of the changes. I update the DESCRIPTION file.

In my opinion, the idea described in the example above is good, but I think you will run into trouble, if you use the general `[` subsetter for this functionality.

What about the result for `lse[c("t10","alias_9"), ]`? Will this double the rows? What if the nodelabels have some of the same values than the rownames? How do you determine the result consistently? I think it is really hard to solve every situation in the most intuitive way, so that users don't run into problems.

My suggestion would be that `[` should only work on the rows and columns and nothing else and that you add a custom function `subsetByNode` to allow for the function you outlined above. This way, it is clear by design, what should work and what shouldn't work.

Cheers,
Felix

**Comment by FelixErnst** [comment]
Alternatively, you could also consider adding a helper function, which turns a value of `nodeLabels` into a `logical` vector, which can be user with `[`, like this:

```
lse[getRowsFromNodeLabel(tse,"alias_9"),]
```

`subsetByNode` could than be just a wrapper:
```
setMethod("subsetByNode","TreeSummarizedExperiment",
  function(x,value){
    x[getRowsFromNodeLabel(x,value),]
  }
)
```

**Comment by FelixErnst** [comment]
Also beaware, that the fix also takes care of subsetting by colnames. Therefore, if you add functions a distinction might be good:

```
setMethod("subsetRowsByNode","TreeSummarizedExperiment",
  function(x,value){
    x[getRowsFromNodeLabel(rowTree(x),value),]
  }
)
setMethod("subsetColsByNode","TreeSummarizedExperiment",
  function(x,value){
    x[,getRowsFromNodeLabel(colTree(x),value)]
  }
)
```

**Comment by fionarhuang** [comment]
Hi Felix,

right, it's better to separate the way to do subsetting, and keep `[ ]` only for rownames/colnames... To simplify the idea,  `subsetByNode` is now created to allow users to play subsetting with nodes. 

For example, with version `1.5.2`, we could do
```
treeR <- ape::rtree(10)
treeC <- ape::rtree(8)
treeC$tip.label <- paste("S", 1:8, sep ="_")
# the count table
count <- matrix(rpois(160, 50), nrow = 20)
rownames(count) <- paste0("entity", 1:20)
colnames(count) <- treeC$tip.label
# The sample information
sampC <- data.frame(condition = rep(c("control", "trt"), 
                                    each = 4),
                    gender = sample(x = 1:2, size = 8, 
                                    replace = TRUE))
rownames(sampC) <- colnames(count)
# build a TreeSummarizedExperiment object
tse <- TreeSummarizedExperiment(assays = list(count),
                                colData = sampC,
                                rowTree = treeR,
                                rowNodeLab = rep(treeR$tip.label, each =2), 
                                colTree = treeC)

# does not work
tse["entity2",]
subsetByNode(x = tse, rowNode = "t1")
subsetByNode(x = tse, rowNode = "t1", colNode = "S_1")
```
