### ISSUE TITLE
Feature request: toTree with na.rm

### ISSUE THREAD

**Issue by FelixErnst** [fionarhuang/TreeSummarizedExperiment#40]
Hi Ruizhu,

I am playing with some real world data and I have a bit of problem with `NA` on the Species level:

[treeData.zip](https://github.com/fionarhuang/TreeSummarizedExperiment/files/5389904/treeData.zip)
```
data <- readRDS("treeData.rda")
toTree(data)
Error in toTree(data) : 
  Not allowed to have duplicated values in the leaf column: Species
```

Maybe I am bit to blind to see it, but I guess there is not an easy option to convert this to a tree is there?

Thanks for any suggestions.

If it is currently not possible, I would like to submit this as a feature request.

Felix

**Comment by FelixErnst** [comment]
I just realized that `resolveLoop` does remove the issue.

However, this leaves a few tip with a lot of NA values. I am not sure, whether this will help me in the end or is a problem.

**Comment by fionarhuang** [comment]
Hi Felix,

Please find the two examples below. The first example, the `NA` value appears in the internal node. To resolve the loop caused by the `NA` value, I add suffix `_1` `_2` to split the loop.  The leaf label is not changed. I guess this is what you like to have? The second example, the `NA` value appears on the leaf level. For this, we can't distinguish the two leaves from the label. That's why the suffix is added to `NA` distinguish them. 

```
library(ggtree)
library(TreeSummarizedExperiment)

# Example 1
df <- rbind.data.frame(c("root", "A1", "A2", NA, "A3"),
                       c("root", "B1", "B2", NA, "B3"))
colnames(df) <- paste0("L", 1:5)
df_1 <- resolveLoop(df)
tree <- toTree(df_1)
ggtree(tree, color = "grey") +
    geom_nodepoint() +
    geom_text2(aes(label = label), angle = 90,
               color = "red", vjust = 2,
               size = 4) 
```

```
# Example 2
df <- rbind.data.frame(c("root", "A1", "A2", NA),
                       c("root", "B1", "B2", NA))
colnames(df) <- paste0("L", 1:4)
df_1 <- resolveLoop(df)
tree <- toTree(df_1)
ggtree(tree, color = "grey") +
    geom_nodepoint() +
    geom_text2(aes(label = label), angle = 90,
               color = "red", vjust = 2,
               size = 4)
```

**Comment by FelixErnst** [comment]
These examples all makes sense and I probably didn't phrase my issue well enough.

In addition to the examples you prepared, I also have this situation in mind:

```
# Example 3
df <- rbind.data.frame(c("root", "A1", "A2", NA),
                       c("root", "B1", NA, NA))
colnames(df) <- paste0("L", 1:4)
df_1 <- resolveLoop(df)
tree <- toTree(df_1)
ggtree(tree, color = "grey") +
    geom_nodepoint() +
    geom_text2(aes(label = label), angle = 90,
               color = "red", vjust = 2,
               size = 4)
```

In this case one of those NA is not necessary anymore, is it? Could this be reflected in `resolveLoop`/`toTree` so that the tree ends on L3 on that arm? Or wouldn't that make sense?

**Comment by fionarhuang** [comment]
I see. I will think how to add this new feature.

**Comment by fionarhuang** [comment]
Hi @FelixErnst ,

I have created a new function `asPhylo` in the new version of `TreeSummarizedExperiment` (https://github.com/fionarhuang/TreeSummarizedExperiment/blob/RELEASE_3_13/R/asPhylo.R), which may have solved this issue.

````
df <- rbind.data.frame(c("root", "A1", "A2", NA),
                       c("root", "B1", NA, NA))
colnames(df) <- paste0("L", 1:4)
tree <- asPhylo(df)
ggtree(tree, color = "grey") +
    geom_nodepoint() +
    geom_text2(aes(label = label), angle = 90,
               color = "red", vjust = 2,
               size = 4)
```

![Screenshot 2021-06-15 at 11 40 27](https://user-images.githubusercontent.com/22393299/122031064-9fa0ba80-cdce-11eb-8e75-cf8e7fccd84d.png)
