### ISSUE TITLE
node.label issue

### ISSUE THREAD

**Issue by antagomir** [fionarhuang/TreeSummarizedExperiment#44]
I tried to make a certain (longer) conversion of a `phyloseq` object into a `TSE` object.  

Minimal example

```
library(phyloseq)
library(MicrobeDS) # devtools::install_github("twbattaglia/MicrobeDS")
data(MovingPictures, package = "MicrobeDS")
obj <- MovingPictures
rowData <- S4Vectors:::make_zero_col_DataFrame(nrow(assays$counts))
rowData <- DataFrame(data.frame(obj@tax_table@.Data))
rowTree <- obj@phy_tree
TreeSummarizedExperiment(rowData = obj@tax_table@.Data, rowTree = rowTree)

```

This fails with: "Error in if (any(sw2) & notALL) { : missing value where TRUE/FALSE needed"

A close analysis shows that `rowTree$node.label` is entirely empty string "" except a single element `rowTree$node.label[[50]]` which is NA. Setting that element to "" as well solves the problem. In this kind of situation (mixture of NA and "") if might be relatively safe to assume that all node.label contents are meant to be empty. 

How about adding a check in allClasses.R before the above-mentioned line and fixing this issue automatically, for instance by converting all NAs into "" at least in the situations described above? And throwing a warning. This could make the function more robust. 

I also see the point in leaving it to the user to provide correct input in the first place, therefore opening an issue instead of PR.

**Comment by fionarhuang** [comment]
Hi, sorry for the delay.
I have fixed this issue by adding `na.rm = TRUE` without overwriting all NAs into "".  The bug was due to the test of `alias_` label. It should be fine for tree that has NA or "" in `node.label`

```
> library(TreeSummarizedExperiment)
> data("tinyTree")
> mm <- matrix(1:40, nrow = 10)
> rownames(mm) <- tinyTree$tip.label
> tinyTree$node.label <- c(NA, "", NA, "", "", NA, NA, NA, NA)
> tinyTree

Phylogenetic tree with 10 tips and 9 internal nodes.

Tip labels:
  t2, t7, t6, t9, t4, t8, ...
Node labels:
  NA, , NA, , , NA, ...

Rooted; includes branch lengths.
> TreeSummarizedExperiment(assay = list(mm), rowTree = tinyTree)
class: TreeSummarizedExperiment 
dim: 10 4 
metadata(0):
assays(1): ''
rownames(10): t2 t7 ... t5 t3
rowData names(0):
colnames: NULL
colData names(0):
reducedDimNames(0):
altExpNames(0):
rowLinks: a LinkDataFrame (10 rows)
rowTree: a phylo (10 leaves)
colLinks: NULL
colTree: NULL
```

**Comment by antagomir** [comment]
Great, thanks!
