### ISSUE TITLE
feature: Adding a slot for information relating to rowData/FeatureIDs in addition to taxonomy

### ISSUE THREAD

**Issue by microsud** [fionarhuang/TreeSummarizedExperiment#59]
Hi @fionarhuang and @FelixErnst 
I was thinking if it would be interesting to store information regarding taxa in TSE. 
For instance,
```
ibrary(mia) # v0.98.22
library(microbiomeDataSets)
tse <- SilvermanAGutData()
tse.sp <- agglomerateByRank(tse, "Species", na.rm = T)
rowdt <- rowData(tse.sp)
rowdt[1:3,4:7]

### OUTPUT### 
DataFrame with 3 rows and 4 columns
                    Order           Family          Genus     Species
              <character>      <character>    <character> <character>
uniformis   Bacteroidales   Bacteroidaceae    Bacteroides   uniformis
ulcerans  Fusobacteriales Fusobacteriaceae  Fusobacterium    ulcerans
piscolens   Synergistales   Synergistaceae Pyramidobacter   piscolens
```

to have information such as: 

```
Genus.Species	Temperature range	Oxygen tolerance	BacDive ID	Type strain	Biosafety level	is.host.associated
Bacteroides.uniformis	mesophilic	anaerobe	1604	ATCC 8492	Risk group	yes
Fusobacterium.ulcerans	mesophilic	anaerobe	5773	DSM 19847	Risk group	yes 

```
Such information can be parsed by user from for example the [The Bacterial Diversity Metadatabase](https://bacdive.dsmz.de/) using [BacDiveR](https://github.com/TIBHannover/BacDiveR) 
For e.g. this can be used for question of weather the taxa that are enriched in a diseased cohort, are mostly anaerobic or aerobic?
What do yo think?

Best wishes,
Sudarshan 

EDIT: https://github.com/FelixErnst/mia/issues/39  linked to this on `mia`

**Comment by antagomir** [comment]
I like it - but since this is specific to microbiome data, would it be more appropriate to have the relevant functionality in mia or another package, and then just use the TSE structure to store that extra information. We could agree about what is the best way.

**Comment by microsud** [comment]
> I like it - but since this is specific to microbiome data, would it be more appropriate to have the relevant functionality in mia or another package, and then just use the TSE structure to store that extra information. We could agree about what is the best way.

Maybe this can also be used for  e.g. in single cell sequencing studies investigating T-Cell repertoires, in case that are databases linked to specific viruses?

**Comment by FelixErnst** [comment]
Maybe a totally stupid question: Doesn't this work now?

I mean you can add whatever you like to `rowData`. Anything you can think off. So this should work right now.

**Comment by microsud** [comment]
Can we already add multiple rowData in a single `TSE`? Like having both taxonomy and physiological properties of each taxon?

**Comment by FelixErnst** [comment]
As I said: you can add as many new columns in any order you want. The rows regards as taxonomic information are selected by `taxonomyRanks(x)`, which you can use to simple subset to: `rowData(x)[,taxonomyRanks(x)]`. This principle holds true for any number of columns in the rowData

**Comment by microsud** [comment]
By nature the properties of these data are different. Taxonomy is hierarchical and physiological not necessarily. So if we `agglomerate*` at family level, then how would the additional columns in rowData like *Oxygen requirement* be treated?

**Comment by FelixErnst** [comment]
That is clearly described in `?agglomerateByRank`: `Metadata from the rowData or colData are retained as defined by archetype.`

If you read up on the `archetype` parameter, you see that you can retain whichever information you want. You can retain always the first element (default) or define any combinations you like. There probably a very high number of combinations.

Try it out for yourself. I promise it works.

**Comment by microsud** [comment]
Okay. I will get back to this after testing with a dummy example data set. Is it okay to keep this issue open for now?

**Comment by FelixErnst** [comment]
I guess so, but this is a `mia` issue not a `TSE` issue, isn't it?

What I realized now, that an addition to `?agglomerateByRank` regarding this, might spell it out more clearly. I thought at the time, that this works out if the box and probably wouldn't need to be spelled out more, since there is not a scenario, which would result in an error.

**Comment by microsud** [comment]
Yes if this can be handled with `mia` functionality.
