### ISSUE TITLE
bug: subsetting doesn't work anymore with saved objects

### ISSUE THREAD

**Issue by FelixErnst** [fionarhuang/TreeSummarizedExperiment#62]
Hi Ruizhu,

at the current state subsetting using `[` doesn't work anymore.

Starting from `both_tse` of the vignette it still works
```
>both_tse[1,]
```

but when using the `GlobalPatterns` object saved in `mia` (See attached file), it does not

```
>GlobalPatterns[1,]
Error in method(object) : 
rowLinks should be NULL when rowTree doesn't exist 
```

I guess thats due to the new `whichTree` column in `rowLinks`, but `updateObject` doesn't resolve the situation.
[GlobalPatterns.zip](https://github.com/fionarhuang/TreeSummarizedExperiment/files/5831729/GlobalPatterns.zip)

Can you have a look, so that saved objects get updated?

Felix

**Comment by fionarhuang** [comment]
Does it work with version `1.99.2`?

**Comment by fionarhuang** [comment]
Hi @FelixErnst , 

I think it should work now with the version `1.99.3`.

Ruizhu

**Comment by FelixErnst** [comment]
I will have a look.

As far as I know, you cannot push a 1.99 to bioconductor git. You have to stay in the 1.7 minor, so that the next relase version can get the 1.8.0 version.

**Comment by fionarhuang** [comment]
>As a special case, any package with version x.99.z is bumped to (x+1) . 0 . (z-z) in release, and (x+1) . 1 . 0 in devel. Thus authors wishing to signify a major change to their package should set y to 99 in their devel package.

If I understand it correctly, the version will become  2.0.0 in the next release according to the rule in the Bioconductor page?
Several big changes have been made. So, probably it is better to have the version as 2.0.0

**Comment by FelixErnst** [comment]
Didn't know that.

**Comment by FelixErnst** [comment]
works
