### ISSUE TITLE
Subsetting an object with duplicated rownames

### ISSUE THREAD

**Issue by FelixErnst** [fionarhuang/TreeSummarizedExperiment#68]
Hi Ruizhu,

I noticed a warning message on some objects:

```
Warning message:
In .numeric_ij(ij = i, x = x, dim = "row") :
  For rows/cols with the same name, only one is output
```

Upon investigation, I noticed that this error is specific to `TSE` objects, whereas `SCE` does the same operation with the same result, but without the warning.

`SummarizedExperiment:::.SummarizedExperiment.charbound` provides the functionality of `.numeric_ij` in `SE` and `SCE` wraps this function in `SingleCellExperiment:::.convert_subset_index`.

Therefore, I am not sure whether the warning is necessary. Whats your take on this?

Felix

**Comment by fionarhuang** [comment]
Hi Felix

For rows with the same name, SCE kind of takes out one of them without warnings. Personally, I think it is more reasonable  give warnings that there are more rows having this name. 

```
> library(TreeSummarizedExperiment)
> set.seed(1)
> 
> tse_a <- makeTSE(include.colTree = FALSE)
> tse_aa <- rbind(tse_a, tse_a)
> 
> rownames(tse_aa)
 [1] "entity1"  "entity2"  "entity3"  "entity4"  "entity5"  "entity6"  "entity7" 
 [8] "entity8"  "entity9"  "entity10" "entity1"  "entity2"  "entity3"  "entity4" 
[15] "entity5"  "entity6"  "entity7"  "entity8"  "entity9"  "entity10"
> tse_aa["entity4", ]
class: TreeSummarizedExperiment 
dim: 1 4 
metadata(0):
assays(1): ''
rownames(1): entity4
rowData names(2): var1 var2
colnames(4): sample1 sample2 sample3 sample4
colData names(2): ID group
reducedDimNames(0):
altExpNames(0):
rowLinks: a LinkDataFrame (1 rows)
rowTree: 1 phylo tree(s) (10 leaves)
colLinks: NULL
colTree: NULL
Warning message:
In .numeric_ij(ij = i, x = x, dim = "row") :
  For rows/cols with the same name, only one is output
> 
> sce_aa <- as(tse_aa, "SingleCellExperiment")
> sce_aa["entity4", ]
class: SingleCellExperiment 
dim: 1 4 
metadata(0):
assays(1): ''
rownames(1): entity4
rowData names(2): var1 var2
colnames(4): sample1 sample2 sample3 sample4
colData names(2): ID group
reducedDimNames(0):
altExpNames(0):
```

**Comment by FelixErnst** [comment]
I totally get your point.

However, this behavior is also deviation from base R:

```
v <- c(a = 1, a = 2)
v["a"]
```

Thats why I am pointing it out. I see the point in both implementations, but the user might expect base R behavior.
I always have to explain students, that the best way to subset is a logical vector and subsetting by name is just syntactic sugar, which can get you in trouble. This time I got in trouble 😄

**Comment by fionarhuang** [comment]
Yeah,  I saw they had a discussion about names somewhere in the closed  issue page of `SE`.   
I tried to find the balance between following the default behavior of base R, and getting users well informed. So,  I set it as a warning instead of an error. 

I mean the warning can be ignored ;)

**Comment by FelixErnst** [comment]
😉
