### ISSUE TITLE
setting rowTree throws error if some rows are dropped

### ISSUE THREAD

**Issue by FelixErnst** [fionarhuang/TreeSummarizedExperiment#74]
Hi Ruizhu,

I am encountering a bug, for which I cannot trace the origin in much detail. Using the example file attached, the following code chunk throws an errors and a warning. (The warning is expected due to mismatching rownames/tip labels)

```
> rowTree(x) <- toTree(resolveLoop(as.data.frame(rowData(x)[,-7])))
Error in `rownames<-`(`*tmp*`, value = c("Bacteroides", "Bifidobacterium",  : 
  invalid rownames length
In addition: Warning message:
In .replace_tree(x = x, value = value, whichTree = whichTree, dim = "row") :
  6 row(s) are dropped due to mismatch with nodes of 'value'
```

When I trace the lines executed in `rowTree`, the error seems to come from this lines
https://github.com/fionarhuang/TreeSummarizedExperiment/blob/4bfecdf6974c41cfadf053e75ad92956a3edccc9/R/allGenerics.R#L78

In this example `nlk` has `106` rows, but x has `111`. Since I start out with `117` and `6` get dropped, the latter is expected, whereas the dimension of `nlk` seem wrong.

Can you have a look? 

[TSE_issue.RData.gz](https://github.com/fionarhuang/TreeSummarizedExperiment/files/5917308/TSE_issue.RData.gz)

Felix

PS: If the rownames match and nothing gets dropped, it works fine.

**Comment by fionarhuang** [comment]
Hi Felix,

Can you try version 1.99.10?

**Comment by FelixErnst** [comment]
works
