### ISSUE TITLE
toTree function causing an error when the levels dont follow an ascending order of the group types

### ISSUE THREAD

**Issue by NPSDC** [fionarhuang/TreeSummarizedExperiment#77]
I am attaching an example of the tree for which I am trying to create a TreeSummarizedExperiment(TSE) object and its corresponding data frame.
[tree](https://drive.google.com/file/d/1ydakUHmlASop8KBNS-puvTT1NXCK-pOU/view?usp=sharing)
[data.frame](https://drive.google.com/file/d/1Zoyuq6PziDY4EJOw6fBDy0zsZRFDTUSJ/view?usp=sharing)

However, if I try to create a tree back from the data frame, I get an error because of the following line
https://github.com/fionarhuang/TreeSummarizedExperiment/blob/master/R/tree_toTree.R#L107

My question is that whether the assumption of the unique group labels at each level to be in ascending order from root to leaves is necessary. I also wanted to make use of aggregation which requires creating a tree using ```toTree``` function in order to label the internal nodes. My plan was to create a local copy and make changes where I comment on the above line but wanted to check if commenting on that line, might impact any downstream analysis/functions.

**Comment by fionarhuang** [comment]
Hi,

Would you please provide an example of code and data? That would be helpful for me to reproduce the issue.

**Comment by NPSDC** [comment]
I am attaching [tree object](https://drive.google.com/file/d/1aqnk0d4w_wx4f1j1N2QwfweX681y3s37/view?usp=sharing), which is an object of phylo class. I convert it into a data frame using the following function
https://github.com/NPSDC/treeTerminusScripts/blob/master/tree_helper_function.R#L10-L25
`df <- getTreeDf(tree)`

However, the below line gives me the following error
`treeN <- toTree(df)`
 
```Please order columns from high to low.```

**Comment by fionarhuang** [comment]
> I am attaching [tree object](https://drive.google.com/file/d/1aqnk0d4w_wx4f1j1N2QwfweX681y3s37/view?usp=sharing), which is an object of phylo class. I convert it into a data frame using the following function
> https://github.com/NPSDC/treeTerminusScripts/blob/master/tree_helper_function.R#L10-L25
> `df <- getTreeDf(tree)`
> 
> However, the below line gives me the following error
> `treeN <- toTree(df)`
> 
> `Please order columns from high to low.`

Hi,
Please provide an example of data frame to reproduce the issue. The function `getTreeDf` depends on other functions, which is not convenient to reproduce a data frame.

**Comment by NPSDC** [comment]
I am attaching a small example, df is the `data.frame` and tree is the corresponding `phylo` object. I am not able to generate tree using `toTree` function and get the error mentioned above.
[temp.zip](https://github.com/fionarhuang/TreeSummarizedExperiment/files/6619256/temp.zip)

**Comment by fionarhuang** [comment]
Hi @NPSDC ,

`toTree` creates a phylo tree that has each path connecting a leaf to the root with the same number of nodes. In your example data, there are several different internal nodes sharing the same node label `unknown`, which would lead to confusion in mapping features to nodes in `TreeSummarizedExperiment`. Hence, this was not allowed in `toTree`, which is mainly designed to serve in `TreeSummarizedExperiment`.

For your example case,  I have created a new function `asPhylo` in the new version of `TSE` ([version 2.0.1](https://github.com/fionarhuang/TreeSummarizedExperiment/tree/RELEASE_3_13)). 
```
library(ggtree)
library(TreeSummarizedExperiment)
tree <- asPhylo(data = df, asNA = c("unknown"))
ggtree(tree, color = "grey") +
    geom_nodepoint() +
    geom_text2(aes(label = label), angle = 90,
               color = "red", vjust = 2,
               size = 4)
```
![Screenshot 2021-06-15 at 11 29 20](https://user-images.githubusercontent.com/22393299/122029235-fefdcb00-cdcc-11eb-8d11-c50cea13286f.png)

**Comment by NPSDC** [comment]
Hi @fionarhuang ,
I appreciate the comments. I had another set of questions. Can I use the above tree created by asPhylo for creating a TSE and whether the above tree can be used as input to treeclimbR? 
Thanks again for the reply.

**Comment by fionarhuang** [comment]
Hi @NPSDC ,

Yes, the tree created by `asPhylo` is a `phylo` object, and hence can be used for creating a `TSE`.   `treeclimbR` has no assumption about the tree structure, so the tree created here can be used as input.

**Comment by NPSDC** [comment]
Thanks
